"""Generate all static export files from data.json."""
import json, csv, io, zipfile, datetime
from pathlib import Path

BASE = Path(__file__).parent
OUT = BASE / "exports"
OUT.mkdir(exist_ok=True)
PUB = BASE / "public"

with open(BASE / "data.json", encoding="utf-8") as f:
    data = json.load(f)

HOME = "6389 E Irwin Pl, Centennial, CO 80112"
DEST = "Children's Hospital Colorado, 13123 E 16th Ave, Aurora, CO 80045"
NOW = datetime.datetime.now().strftime("%Y-%m-%d")
g1 = [d for d in data if d["group"] == 1]
g2 = [d for d in data if d["group"] == 2]

# === CSV ===
buf = io.StringIO()
w = csv.writer(buf)
w.writerow(["Group","Facility Name","Address","Phone","Hours","New Patients","Private Pay","Distance (mi)","Services","Website","Confidence","Notes"])
for d in data:
    w.writerow([
        "Within 10 mi of Home" if d["group"] == 1 else "I-225 Commute Corridor",
        d["name"], d["address"], d["phone"], d["hours"],
        d["new_patients"], d["private_pay"], d["distance_mi"],
        d["services"], d.get("website",""), d["confidence"], d.get("notes","")
    ])
csv_text = buf.getvalue()
(OUT / "adult-daycare.csv").write_text(csv_text, encoding="utf-8")
(PUB / "adult-daycare.csv").write_text(csv_text, encoding="utf-8")
print(f"CSV: {len(data)} rows")

# === JSON ===
json_out = json.dumps({
    "title": "Adult Day Care Directory — Centennial & Aurora, CO",
    "home_address": HOME,
    "destination": DEST,
    "generated": NOW,
    "total": len(data),
    "group_1_within_10mi": g1,
    "group_2_commute_corridor": g2
}, indent=2, ensure_ascii=False)
(OUT / "adult-daycare.json").write_text(json_out, encoding="utf-8")
(PUB / "adult-daycare.json").write_text(json_out, encoding="utf-8")
print(f"JSON: {len(json_out):,} bytes")

# === Markdown ===
md = f"# Adult Day Care Directory — Centennial & Aurora, CO\n\n"
md += f"> **Home:** {HOME}\n"
md += f"> **Destination:** {DEST}\n"
md += f"> **Generated:** {NOW}\n\n"
for label, items in [("Group 1: Within 10 Miles of Home", g1), ("Group 2: I-225 Commute Corridor (Within 5 mi)", g2)]:
    if not items:
        continue
    md += f"## {label}\n\n"
    md += "| Facility | Address | Phone | Hours | New Patients | Private Pay | Distance | Confidence |\n"
    md += "|----------|---------|-------|-------|:------------:|:-----------:|:--------:|:----------:|\n"
    for d in items:
        md += f"| {d['name']} | {d['address']} | {d['phone']} | {d['hours']} | {d['new_patients']} | {d['private_pay']} | {d['distance_mi']} mi | {d['confidence']} |\n"
    md += "\n"
md += "---\n*MIT License | Generated by AEPT-AI*\n"
(OUT / "adult-daycare.md").write_text(md, encoding="utf-8")
(PUB / "adult-daycare.md").write_text(md, encoding="utf-8")
print(f"Markdown: {len(md):,} bytes")

# === HTML (standalone) ===
def esc(s):
    return str(s).replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")

html = f"""<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Adult Day Care Directory</title>
<style>body{{font-family:-apple-system,sans-serif;margin:40px;color:#1c1c1e}}
table{{border-collapse:collapse;width:100%}}th,td{{padding:8px 10px;border:1px solid #ddd;text-align:left;font-size:12px}}
th{{background:#f2f2f7;font-weight:600;text-transform:uppercase;font-size:10px;letter-spacing:.5px}}
tr:nth-child(even){{background:#fafafa}}h1{{font-size:20px}}h2{{font-size:16px;margin-top:24px}}
.y{{background:#e8f5e9;color:#2e7d32;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600}}
.n{{background:#ffebee;color:#c62828;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600}}
.u{{background:#f5f5f5;color:#999;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:600}}</style></head><body>
<h1>Adult Day Care Directory</h1>
<p>Centennial &amp; Aurora, CO | Generated {NOW}</p>
<p><strong>Home:</strong> {esc(HOME)} | <strong>Destination:</strong> {esc(DEST)}</p>"""

for label, items in [("Group 1: Within 10 Miles of Home", g1), ("Group 2: I-225 Commute Corridor", g2)]:
    if not items:
        continue
    html += f"<h2>{label} ({len(items)})</h2>"
    html += "<table><tr><th>Facility</th><th>Address</th><th>Phone</th><th>Hours</th><th>New Patients</th><th>Private Pay</th><th>Distance</th><th>Services</th></tr>"
    for d in items:
        np_cls = "y" if d["new_patients"] == "Y" else "n" if d["new_patients"] == "N" else "u"
        pp_cls = "y" if d["private_pay"] == "Y" else "n" if d["private_pay"] == "N" else "u"
        html += f'<tr><td><strong>{esc(d["name"])}</strong></td><td>{esc(d["address"])}</td><td>{esc(d["phone"])}</td><td>{esc(d["hours"])}</td>'
        html += f'<td><span class="{np_cls}">{d["new_patients"]}</span></td><td><span class="{pp_cls}">{d["private_pay"]}</span></td>'
        html += f'<td>{d["distance_mi"]} mi</td><td style="max-width:300px;font-size:11px">{esc(d["services"])}</td></tr>'
    html += "</table>"
html += "</body></html>"
(OUT / "adult-daycare.html").write_text(html, encoding="utf-8")
print(f"HTML: {len(html):,} bytes")

# === LaTeX ===
def tex_esc(s):
    return str(s).replace("&","\\&").replace("_","\\_").replace("#","\\#").replace("%","\\%").replace("$","\\$").replace("{","\\{").replace("}","\\}")

tex = r"""\documentclass[11pt,landscape]{article}
\usepackage[margin=0.8in]{geometry}
\usepackage{booktabs,longtable,hyperref}
\usepackage[utf8]{inputenc}
\title{Adult Day Care Directory --- Centennial \& Aurora, CO}
\author{Generated by AEPT-AI}
\date{""" + NOW + r"""}
\begin{document}
\maketitle
\textbf{Home:} """ + tex_esc(HOME) + r""" \\
\textbf{Destination:} """ + tex_esc(DEST) + r"""
\vspace{1em}
"""

for label, items in [("Group 1: Within 10 Miles of Home", g1), ("Group 2: I-225 Commute Corridor", g2)]:
    if not items:
        continue
    tex += f"\\section*{{{label} ({len(items)})}}\n"
    tex += "\\begin{longtable}{p{3.5cm}p{4cm}p{2.2cm}p{3cm}p{1.5cm}p{1.5cm}p{1.2cm}}\n"
    tex += "\\toprule\nFacility & Address & Phone & Hours & New Pts & Pvt Pay & Dist \\\\\n\\midrule\n\\endhead\n"
    for d in items:
        tex += f"{tex_esc(d['name'])} & {tex_esc(d['address'])} & {d['phone']} & {tex_esc(d['hours'])} & {d['new_patients']} & {d['private_pay']} & {d['distance_mi']} mi \\\\\n"
    tex += "\\bottomrule\n\\end{longtable}\n\n"
tex += "\\end{document}\n"
(OUT / "adult-daycare.tex").write_text(tex, encoding="utf-8")
(PUB / "adult-daycare.tex").write_text(tex, encoding="utf-8")
print(f"LaTeX: {len(tex):,} bytes")

# === ZIP bundle ===
zip_path = OUT / "adult-daycare-directory.zip"
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
    zf.writestr("adult-daycare.csv", csv_text)
    zf.writestr("adult-daycare.json", json_out)
    zf.writestr("adult-daycare.md", md)
    zf.writestr("adult-daycare.html", html)
    zf.writestr("adult-daycare.tex", tex)
# Copy zip to public for download
import shutil
shutil.copy2(zip_path, PUB / "adult-daycare-directory.zip")
print(f"ZIP: {zip_path.stat().st_size:,} bytes")

print(f"\nAll exports complete: {len(data)} facilities, 6 formats")
